package com.almlk.swiftkey.ime;

import android.content.Context;
import android.content.res.XmlResourceParser;
import android.util.AttributeSet;
import android.util.Xml;
import com.almlk.swiftkey.model.KeySpec;
import com.almlk.swiftkey.model.KeyboardLayout;
import com.almlk.swiftkey.model.KeyboardLayouts;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import org.xmlpull.v1.XmlPullParser;

/** Loads editable key labels, secondary labels and alternatives from res/xml/kbd_*.xml. */
public final class KeyboardXmlParser {
  private static final java.util.HashMap<Integer, KeyboardLayout> LAYOUT_CACHE =
      new java.util.HashMap<Integer, KeyboardLayout>();

  private KeyboardXmlParser() {}

  public static KeyboardLayout load(Context context, int xmlResource, boolean rtl) {
    int cacheKey = xmlResource * 2 + (rtl ? 1 : 0);
    synchronized (LAYOUT_CACHE) {
      KeyboardLayout cached = LAYOUT_CACHE.get(Integer.valueOf(cacheKey));
      if (cached != null) return cached;
    }
    List<List<KeySpec>> rows = new ArrayList<List<KeySpec>>();
    List<KeySpec> currentRow = null;
    int layoutDigitType = -1;
    int layoutKeyboardId = -1;
    XmlResourceParser parser = context.getResources().getXml(xmlResource);
    try {
      int event;
      while ((event = parser.next()) != XmlPullParser.END_DOCUMENT) {
        if (event == XmlPullParser.START_TAG) {
          String tag = parser.getName();
          AttributeSet attributes = Xml.asAttributeSet(parser);
          if ("Keyboard".equals(tag)) {
            layoutDigitType = parseDigitType(attributes);
            layoutKeyboardId = parseKeyboardLayoutId(attributes);
          } else if ("Row".equals(tag)) {
            int rowType = attributeInt(attributes, "rowType", 0);
            if ("extended".equals(attributeValue(attributes, "rowType", ""))) {
              rowType = 1;
            }
            // The number row is generated by SmartKeyboardView and controlled by swipe.
            if (rowType == 1) {
              currentRow = null;
            } else {
              currentRow = new ArrayList<KeySpec>();
              rows.add(currentRow);
            }
          } else if ("Key".equals(tag) && currentRow != null) {
            KeySpec key = readKey(context, attributes);
            if (key != null) currentRow.add(key);
          }
        }
      }
    } catch (Exception exception) {
      rows.clear();
    } finally {
      parser.close();
    }
    KeyboardLayout result = new KeyboardLayout(rows, rtl, layoutDigitType, layoutKeyboardId);
    if (rows.size() > 0) {
      synchronized (LAYOUT_CACHE) {
        LAYOUT_CACHE.put(Integer.valueOf(cacheKey), result);
      }
    }
    return result;
  }

  public static KeyboardLayout loadLetters(
      Context context,
      int xmlResource,
      boolean rtl,
      boolean shifted,
      String editorContext,
      String language) {
    KeyboardLayout source = load(context, xmlResource, rtl);
    List<List<KeySpec>> rows = new ArrayList<List<KeySpec>>();
    for (int rowIndex = 0; rowIndex < source.rows.size(); rowIndex++) {
      List<KeySpec> row = source.rows.get(rowIndex);
      List<KeySpec> transformed = new ArrayList<KeySpec>();
      for (int keyIndex = 0; keyIndex < row.size(); keyIndex++) {
        KeySpec key = row.get(keyIndex);
        String label = key.label;
        int code = key.code;
        if (!rtl
            && shifted
            && code > 0
            && label.length() == 1
            && Character.isLetter(label.charAt(0))) {
          label = label.toUpperCase(Locale.US);
        }
        String alternates = key.alternatives;
        if (code == KeySpec.SPACE) {
          label = rtl ? "العربية" : "English (US)";
        } else if (rowIndex == source.rows.size() - 1 && keyIndex == row.size() - 2 && code >= 0) {
          if ("email".equals(editorContext)) {
            label = "@";
            code = '@';
          } else if ("url".equals(editorContext)) {
            label = "/";
            code = '/';
          } else {
            // Round 58: النقطة أساسية في العربية أيضاً — وعلامة الاستفهام في الحرف البديل
            label = ".";
            code = '.';
            if (rtl && (alternates == null || !alternates.contains("؟"))) {
              alternates =
                  alternates == null || alternates.length() == 0 ? "؟" : "؟ " + alternates;
            }
          }
        }
        transformed.add(
            new KeySpec(
                label,
                key.subLabel,
                alternates,
                code,
                key.weight,
                key.popupKeyboardRes,
                key.edgeFlags));
      }
      rows.add(transformed);
    }
    return new KeyboardLayout(rows, rtl, source.digitType, source.keyboardLayoutId);
  }

  /**
   * Reads the layout native digit type from the raw Keyboard tag. Accepts both the compiled
   * enum integer (0 western, 1 arabic) and the literal names, using raw attributes only.
   */
  private static int parseDigitType(AttributeSet attributes) {
    int value = attributeInt(attributes, "digitType", -1);
    String name = attributeValue(attributes, "digitType", "");
    if ("western".equals(name)) {
      value = 0;
    } else if ("arabic".equals(name)) {
      value = 1;
    }
    return value == 0 || value == 1 ? value : -1;
  }

  /** Reads the declared layout enum id, accepting compiled integers and literal tokens. */
  private static int parseKeyboardLayoutId(AttributeSet attributes) {
    int value = attributeInt(attributes, "keyboardLayout", -1);
    if (value >= 0) {
      return value;
    }
    return KeyboardLayouts.idForToken(attributeValue(attributes, "keyboardLayout", ""));
  }

  private static KeySpec readKey(Context context, AttributeSet attributes) {
    String label = attributeValue(attributes, "keyLabel", "");
    String trail = attributeValue(attributes, "trailLabel", "");
    String popup = normalizePopupCharacters(attributeValue(attributes, "popupCharacters", ""));
    String output = attributeValue(attributes, "keyOutputText", "");
    String rawCode = attributeValue(attributes, "codes", "");
    int popupKeyboard = attributeResource(attributes, "popupKeyboard", 0);
    int edgeFlags = parseEdgeFlags(attributeValue(attributes, "keyEdgeFlags", ""), 0);
    boolean spacer = attributeBoolean(attributes, "isSpacer", false);

    if (spacer) {
      return null;
    }
    int code = parseCode(rawCode, label, output);
    String shownLabel = label.length() == 0 ? output : label;
    return new KeySpec(shownLabel, trail, popup, code, weightFor(code), popupKeyboard, edgeFlags);
  }

  private static int attributeIndex(AttributeSet attributes, String name) {
    for (int index = 0; index < attributes.getAttributeCount(); index++) {
      if (name.equals(attributes.getAttributeName(index))) {
        return index;
      }
    }
    return -1;
  }

  private static String attributeValue(AttributeSet attributes, String name, String fallback) {
    int index = attributeIndex(attributes, name);
    if (index < 0) {
      return fallback;
    }
    String value = attributes.getAttributeValue(index);
    return value == null ? fallback : value;
  }

  private static int attributeResource(AttributeSet attributes, String name, int fallback) {
    int index = attributeIndex(attributes, name);
    return index < 0 ? fallback : attributes.getAttributeResourceValue(index, fallback);
  }

  private static int attributeInt(AttributeSet attributes, String name, int fallback) {
    int index = attributeIndex(attributes, name);
    return index < 0 ? fallback : attributes.getAttributeIntValue(index, fallback);
  }

  private static boolean attributeBoolean(AttributeSet attributes, String name, boolean fallback) {
    int index = attributeIndex(attributes, name);
    return index < 0 ? fallback : attributes.getAttributeBooleanValue(index, fallback);
  }

  private static float weightFor(int code) {
    if (code == KeySpec.SPACE) return 4.5f;
    if (code == KeySpec.ENTER || code == KeySpec.DELETE || code == KeySpec.MODE) return 1.35f;
    if (code == KeySpec.SHIFT) return 1.35f;
    if (code == KeySpec.EMOJI) return 1.15f;
    if (code == KeySpec.MIC) return 1.1f;
    return 1f;
  }

  private static int parseCode(String rawCode, String label, String output) {
    if (rawCode != null) {
      int comma = rawCode.indexOf(',');
      String first = comma < 0 ? rawCode : rawCode.substring(0, comma);
      try {
        return Integer.parseInt(first.trim());
      } catch (NumberFormatException ignored) {
      }
    }
    String text = output.length() == 0 ? label : output;
    return text.length() == 0 ? 0 : text.codePointAt(0);
  }

  private static String normalizePopupCharacters(String text) {
    if (text == null || text.length() == 0 || text.matches(".*\\s+.*")) return value(text);
    StringBuilder result = new StringBuilder();
    for (int offset = 0; offset < text.length(); ) {
      int codePoint = text.codePointAt(offset);
      if (result.length() > 0) result.append(' ');
      result.append(text.substring(offset, offset + Character.charCount(codePoint)));
      offset += Character.charCount(codePoint);
    }
    return result.toString();
  }

  private static int parseEdgeFlags(String text, int fallback) {
    if (text == null) return fallback;
    int result = 0;
    if (text.indexOf("left") >= 0) result |= 1;
    if (text.indexOf("right") >= 0) result |= 2;
    try {
      if (result == 0) result = Integer.parseInt(text);
    } catch (NumberFormatException ignored) {
    }
    return result == 0 ? fallback : result;
  }

  private static String value(String text) {
    return text == null ? "" : text;
  }
}
